version: 2.1

executors:
  build:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/app

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build:
    parameters:
      go-version:
        type: string
      golangci-lint-version:
        type: string

    executor:
      name: build
      go-version: << parameters.go-version >>

    steps:
      - checkout

      - go_mod_download

#      - run:
#          name: Install GolangCI-Lint
#          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>
#      - run:
#          name: Run GolangCI-Lint
#          command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet
      - run:
          name: Run Tests
          command: go test -cover -race -v ./...
    # https://circleci.com/docs/2.0/google-auth/
    # https://circleci.com/docs/2.0/google-container-engine/
    # https://cloud.google.com/container-registry/docs/pushing
  push-image:
    machine: true
    steps:
      - checkout
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: docker build --rm=false -t asia.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 -f ./docker/app/Dockerfile.dev .
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud docker -- push asia.gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1

workflows:
  golang-workflow:
    jobs:
      - build:
          go-version: "1.12"
          golangci-lint-version: "1.15.0"
      - push-image:
          requires:
            - build
          filters:
            branches:
              only: 
                - master
                - develop
          
